### ISSUE TITLE
Silly dbt

### ISSUE THREAD

**Issue by bee0507** [guardianangel0507/vrms#10]
Wats diffrnce btwn SITE_URL and SITE_ROOT
Not differnce, I mean why cant we use SITE_ROOT instead of SITE_URL or vice versa
Even njan cheythm noki angane, error oke vanu..apoyanu me orthe wats the differenc like ..
Ithre nalayitm ee silly doubt ipoyano vanne nnu orth vishamam indtto😂

**Comment by guardianangel0507** [comment]
SITE_ROOT = Specific to the Server - That is file or script accessed by the server-side uses SITE_ROOT. Servers access files using absolute location.
SITE_URL = Specific to the Browser - Files or Scripts accessed by the Browser-Side or we say Client-side uses SITE_URL. Because browsers access files using URL.

Try printing both values in tester.php.
You will come to know.

**Comment by bee0507** [comment]
Oke thankU
