### ISSUE TITLE
Dbt

### ISSUE THREAD

**Issue by bee0507** [guardianangel0507/vrms#8]
![Screen Shot 2020-09-18 at 7 02 03 PM](https://user-images.githubusercontent.com/69832828/93603808-23fe1280-f9e2-11ea-8c08-be020493a512.png)

One doubt regarding this. Ivde naml two times Login/Register kodthu. One n list section in navigation bar, another one div ayit kodthu le. Aa div nthina..I mean page il ath kanulelo..then why angane cheythe..
pine that href to Login/Register, we gav as https://vrms.com/public/default/home-route.php. How is that possible..I mean vrms.com ?
 Njan /vrms run cheythit when i click on Login/Register it shld take me to that home-route page na ? But angane pokunila. Its shows like this..
![Screen Shot 2020-09-18 at 7 06 07 PM](https://user-images.githubusercontent.com/69832828/93604788-7e4ba300-f9e3-11ea-820a-3436c143e231.png)

**Comment by guardianangel0507** [comment]
Answer for 1st Question: 
Check assets/css/lander.css. There are selectors called "#auth" under different "screen selectors - ( look for @media screen )", which has some special styling properties, which shows up only when the site is accessed using mobile phones. Simply, The first Login/Register shows up when the site is displayed on large screens, and the second one shows when accessed from mobile screens. It's with the CSS.

Answer for 2nd Question: It is possible only in my system because that's the server address in my system. "**https://vrms.com**" is the server address registered in my system.
What is the server address of yours?
"**http://localhost:8080/vrms/**" right?
So replace all "**https://vrms.com**" to "**http://localhost:8080/vrms/**".

**Comment by bee0507** [comment]
![Screen Shot 2020-09-19 at 11 18 00 AM](https://user-images.githubusercontent.com/69832828/93660247-6408d800-fa6a-11ea-911a-56a0bfb10a33.png)
Is this normal.? bcz I tried clickng the 'sign up' button in home-route page but it was not working. 
Apo I was checking. Clicking on Login/Register shuld take to default-home. Avde it goes to authorization.php. Athil $formName = 'signin' initiliased. Apo aa page il div id="signin-form" ale work avuolu..
Aa dbt avde nikate..
$defaultHomeIndex->authNav. ee authNav ile value pass avum to header.php na ? That means it will display two buttons signin and signup. ale

Ee register.php il aanu formName session = signup kodthekune..so which page is calling that...na authorization page il if formName=signup anel it calls to register.php ...ale


Will u be able to understand anythng i told now.its all messy up/ The thing is when i click on signin or signup button on home-route page..its not working..apo I was kind of debugging here nd there but not getting any conclusion as to why thats not happening

**Comment by guardianangel0507** [comment]
Read the error in Console Carefully. It says, "Jquery must be included before Bootstrap's JavaScript", see? That means every other javascript files that use JQuery must be added after the jquery file. I guess your Jquery files are not present in header.php or are below other files. Check my header.php.

Did you check the default-home.php? The header, authorization, and footer are included inside default-home.php like it is a container. 
$formName = signin is not for signin-form to "work". It is to make the signin-form as the default form to show. The default form that should show at first.

Later in signup-form, during registration, if any error occurs, it should show the signup form after checking the data submitted to register.php. So, in register.php, we $_SESSION['formName'] = "signup".

And the same with sign-in form too. Check login.php and register.php in lib/scripts.

The concept is, when u open a website, first it should show the login page. And then, if the user wants to register, then only, you have to show the register page.

$_SESSION['signup'] and $_SESSION['signin'] are not for "calling" the forms. That's done by the signup, signin buttons. Those 2 session variables are for displaying correct form and displaying errors and messages. 

In authorization.php, that's why we check for $_SESSION['formName']. This session variable is set in either login.php or in register.php. They are used in authorization.php only to display any errors or messages. Look at lines 74 and 169 in authorization.php.
I think you have to go through the code and find out wherever are the variables used.

If a variable is initialized or declared in a php page, check that php page itself and all included php pages inside that php page.

Now, Don't look at the address bar to find which page is displayed. In home-route,php, we use the Template class to display different pages of different users. Go through home-route.php. It's just that home-route.php acts a conditional container, which displays different pages according to the user types.

**Comment by bee0507** [comment]
/*Read the error in Console Carefully. It says, "Jquery must be included before Bootstrap's JavaScript", see? That means every other javascript files that use JQuery must be added after the jquery file. I guess your Jquery files are not present in header.php or are below other files. Check my header.php.*/
![Screen Shot 2020-09-19 at 12 42 34 PM](https://user-images.githubusercontent.com/69832828/93661510-f6fb3f80-fa75-11ea-940b-64cad8e1a19a.png)
Ithale..jquery . Its same as urs only.

**Comment by guardianangel0507** [comment]
Check the SITE_URL in your config.php. And also check the name and path of jquery file is as same as in yours

**Comment by guardianangel0507** [comment]
Also check the default-home.php and footer.php, for whether there are all files needed.

**Comment by bee0507** [comment]
Gotcha..name of jqueryfile was different. Thank youu
