### ISSUE TITLE
parameter dbt

### ISSUE THREAD

**Issue by bee0507** [guardianangel0507/vrms#9]
![Screen Shot 2020-09-30 at 11 17 19 AM](https://user-images.githubusercontent.com/69832828/94647672-950cc680-030e-11eb-93b0-574d22c6a069.png)

why not pass through parameter as before?

**Comment by bee0507** [comment]
unset the session ?

**Comment by guardianangel0507** [comment]
Parameter passing removed because it is more efficient than creating the Message Handler everywhere we need to print errors and messages, instead, we could utilize sessions to print the errors right after the header. Check header.php.

the unset session is because, once an error or message is printed, we don't need the same error and message to be present there again right?

**Comment by bee0507** [comment]
Ohkkk
